### ISSUE TITLE
On Contact Us page:

### ISSUE THREAD

**Issue by ambergkim** [amgranad/desgn-worth#128]
Font family should be changed to brand fonts
DONE: Change email link on contact page to a "mailto:" link ??
* turned into a link but we have no email so placed hashtag instead.
DONE: Background should take up the entire background in mobile view

**Comment by ambergkim** [comment]
What fonts should be changed? These are the settings for the contact page
p {
  font-size: 50px;
  font-style: 'Ubuntu', sans-serif;
}

h1, h2, h3 {
  font-style: 'Cabin', sans-serif;
}

**Comment by alicialycan** [comment]
Done
