### ISSUE TITLE
Main Form & Quote: Project Calculations & Breakdown

### ISSUE THREAD

**Issue by ambergkim** [amgranad/desgn-worth#14]
# Requirements
* calculates user input for project
* populates calculations & breakdown in the proposal section

# Form Input
* type of project: 1 pages, basic 5 pager, eCommerce
* Number of Pages/Products
* wordpress vs hand coded.

# Proposal. Possible sections
* breakdown of big tasks
* objectives
* strategy
* timeline
* Cost breakdown
* what is required from the client
* benefits

**Comment by alicialycan** [comment]
Package Costs:
(1) BASIC: $5,000 (8 weeks)
(2) ECOMMERCE: $15,000 (*5 products) (24 weeks)
-$150/pg (5 min)
-$150/product (5 min)
-$750 (5) (2 weeks)
