### ISSUE TITLE
Things we noticed on the monitor tonight

### ISSUE THREAD

**Issue by alicialycan** [amgranad/desgn-worth#163]
DONE: Quote page - need to add courses add on and explanation, and need to add explanations for extra help options/feature them on main quote page.

Form 1 - need to add breaks for flow

DONE: Text needs to be larger on many of the pages particularly check mobile font sizes; need consistency through pages

**Comment by ambergkim** [comment]
@alicialycan What do you mean by Form1 breaks? @alicialycan

**Comment by alicialycan** [comment]
Fixed.
